name: DevOps Troubleshooting Toolkit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  toolkit-linter:
    name: Validate Markdown, Shell Scripts, and Toolkit Structure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Markdown linting
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint '**/*.md' --ignore node_modules

      # Shell script linting
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck on scripts
        run: |
          if [ -d "./scripts" ]; then
            find ./scripts -type f -name "*.sh" -exec shellcheck {} +
          else
            echo "No scripts/ directory found."
          fi

      # Basic directory structure validation
      - name: Validate essential folders
        run: |
          REQUIRED_DIRS="cloud containers databases kubernetes terraform linux observability scripts"
          for dir in $REQUIRED_DIRS; do
            if [ ! -d "$dir" ]; then
              echo "::error::Missing required folder: $dir"
              exit 1
            fi
          done

      - name: Confirm README and License files
        run: |
          REQUIRED_FILES="README.md LICENSE"
          for file in $REQUIRED_FILES; do
            if [ ! -f "$file" ]; then
              echo "::error::Missing required file: $file"
              exit 1
            fi
          done
